name: Deploys3

on:
  push:
    branches:
      - master  # Adjust the branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{secrets.AWS_SESSION_TOKEN}}
          aws-region: us-east-1  # Change to your desired AWS region

      - name: Deploy to S3
        run: |
          aws s3 sync ./path/to/local/files s3://github-demo2
